name: bitcoin_base_i
description: A comprehensive Bitcoin library, adjusted to support Dart 2. 
version: 0.5.0
repository: "https://github.com/irulast/bitcoin_base_i"
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  pointycastle: ^3.7.3
  convert: ^3.1.1
  typed_data: ^1.3.2
  tuple: ^2.0.2

dev_dependencies:
  http: ^0.13.4
  lints: ^1.0.0
  flutter_test:
    sdk: flutter
