name: bitcoin_base
description: A comprehensive Bitcoin library for creating/signing and spending P2PK, P2PKH, P2SH, P2WPKH, P2WSH, Taproot ...
version: 0.5.0
homepage: "https://github.com/MohsenHaydari/bitcoin_base"
repository: "https://github.com/MohsenHaydari/bitcoin_base"
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  pointycastle: ^3.7.3
  convert: ^3.1.1
  typed_data: ^1.3.2
  tuple: ^2.0.2

dev_dependencies:
  http: ^0.13.4
  lints: ^1.0.0
  flutter_test:
    sdk: flutter
